apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: kpnowwithingress
    labels:
        app: kpnowwithingress
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: kpnowwithingress531-kpnowwithingress.kpnowwithingress-dns-b869e0ab.hcp.centralus.azmk8s.io
          http:
            paths:
            - path: /
              backend:
                serviceName: kpnowwithingress
                servicePort: 80
CMD