apiVersion: v1
kind: Service
metadata:
    name: kpjavakubernetes
    labels:
        app: kpjavakubernetes
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: kpjavakubernetes